export const INSURANCE_LIST_REQUEST = 'INSURANCE_LIST_REQUEST'
export const INSURANCE_LIST_SUCCESS = 'INSURANCE_LIST_SUCCESS'
export const INSURANCE_LIST_FAIL = 'INSURANCE_LIST_FAIL'

export const INSURANCE_EDIT_REQUEST="INSURANCE_EDIT_REQUEST"
export const INSURANCE_EDIT_SUCCESS="INSURANCE_EDIT_SUCCESS"
export const INSURANCE_EDIT_FAIL="INSURANCE_EDIT_FAIL"
export const INSURANCE_EDIT_RESET="INSURANCE_EDIT_RESET"

